<$ROOT/mkconfig

WAST=`{ls *.wast}
JSON=${WAST:%.wast=%.json}
WASM=`{ls *.wasm}
DIS=${WASM:%.wasm=%.dis}
DISPATCH=${JSON:%.json=%.0_dispatch.dis}
INCLUDES=-I../module
TESTOUT=${JSON:%.json=%.testout}

%.json: %.wast
	wast2json $stem.wast && mk

%.dis: %.wasm
	inferno wasm/w2d $stem.wasm

%.0_dispatch.b: %.json
	inferno specgen $stem.json

%.dis: %.b
	limbo -I../module $stem.b

%.testout: %.json
	(cd ..; inferno spectest test/$stem.json) > $stem.testout

all:V:  $JSON $DIS $DISPATCH

clean:V:
	rm -f *.wasm *.json *.dis *_dispatch.b

test:V: $TESTOUT
	grep FAIL *.testout
