<$ROOT/mkconfig

TARG=w2d.dis\

MODULES=\
	types.m\
	$ROOT/appl/cmd/limbo/arg.m\
	$ROOT/appl/cmd/limbo/isa.m\
	asm.b\
	desc.b\
	dis.b\
	emit.b\
	entry.b\
	frame.b\
	w2d.b\
	links.b\
	main.b\
	module.b\
	sbl.b\
	util.b\
	simwasm.b\
	wxlate.b\
	wasm.m\
	wasmisa.m\
	optab.m\
	wasmdas.b\

SYSMODULES=\
	bufio.m\
	draw.m\
	keyring.m\
	math.m\
	string.m\
	sys.m\

DISBIN=../../dis/wasm

<$ROOT/mkfiles/mkdis

LIMBOFLAGS=-I$MODDIR\
	-I$ROOT/appl/cmd/limbo\
